reload("user.plugins.configs.alpha")
reload("user.plugins.configs.nvim-tree")
reload("user.plugins.configs.telescope")
reload("user.plugins.configs.treesitter")
reload("user.plugins.configs.gitlinker")
